version: '3'
services:
  app:
    build: .
    command: python manage.py run_gunicorn
    environment:
      - FLASK_CONFIG=production
    networks:
      - globalproxy_default
      - default
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:3.2.8
    volumes:
      - cache:/data
    restart: always

volumes:
  cache:
    driver: local

networks:
  globalproxy_default:
    external: true