version: '3'
services:
  scaffold:
    build: .
    volumes:
     - .:/usr/src/app
    command: python manage.py runserver --host=0.0.0.0
    environment:
     - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
     - FLASK_CONFIG=development
    depends_on:
      - redis
    ports:
      - 5000:5000
  redis:
    image: redis:3.2.8
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
