version: '3'
services:
  app:
    build: .
    command: python manage.py run_gunicorn
    environment:
      - FLASK_CONFIG=production
    depends_on:
      - redis
    ports:
      - 80:80
    restart: always
  redis:
    image: redis:3.2.8
    volumes:
      - cache:/data
    restart: always

volumes:
  cache:
    driver: local
